[package]
name = "tp-app"
description = "TruckPaint desktop application."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "truckpaint"
path = "src/main.rs"

[dependencies]
tp-i18n.workspace = true
sys-locale.workspace = true
tp-vehicles.workspace = true
tp-pack.workspace = true
semver.workspace = true
tp-core.workspace = true
tp-ui.workspace = true
tp-text.workspace = true
tp-file.workspace = true
tp-render.workspace = true
image.workspace = true
resvg.workspace = true
rfd.workspace = true
eframe.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
directories.workspace = true
ron.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
tempfile.workspace = true
zip.workspace = true
texpresso.workspace = true

[lints]
workspace = true
